"""Column-level lineage commands.

Reads the pre-built lineage.json artifact (NOT manifest.json — lineage is its
own artifact, generated by `meta lineage build` or in CI). Queries are O(V+E)
on a rustworkx-backed graph.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Any

from dbt_meta.lineage import LineageGraph, find_lineage_artifact, load_artifact
from dbt_meta.lineage.graph import make_node_id, split_node_id


@lru_cache(maxsize=2)
def _get_cached_graph(artifact_path: str) -> tuple[LineageGraph, dict[str, Any]]:
    """LRU-cached loader. Two slots: prod and dev artifacts can coexist."""
    return load_artifact(artifact_path)


def _resolve_node_id(graph: LineageGraph, ref: str) -> str | None:
    """Best-effort lookup: accepts 'model.column' or 'model:column' notation."""
    if graph.has_node(ref):
        return ref
    # Try '<model>:<col>' shorthand
    if ":" in ref:
        model, _, col = ref.rpartition(":")
        candidate = make_node_id(model, col)
        if graph.has_node(candidate):
            return candidate
    return None


def _format_node(graph: LineageGraph, node_id: str) -> dict[str, Any]:
    payload = graph.get_node(node_id) or {}
    model, column = split_node_id(node_id)
    return {
        "id": node_id,
        "model": payload.get("model", model),
        "column": payload.get("column", column),
        "data_type": payload.get("data_type", ""),
    }


def column_lineage(
    artifact_path: str,
    column_ref: str,
    direction: str = "upstream",
) -> dict[str, Any] | None:
    """Return upstream or downstream lineage for a single column.

    Args:
        artifact_path: Path to lineage.json.
        column_ref: 'model.column' or 'model:column'.
        direction: 'upstream' (ancestors) or 'downstream' (descendants).

    Returns:
        dict with target node + direct + transitive lineage, or None if
        the column is not in the graph.
    """
    graph, metadata = _get_cached_graph(artifact_path)
    target = _resolve_node_id(graph, column_ref)
    if target is None:
        return None

    if direction == "upstream":
        direct = graph.parents(target)
        all_related = graph.ancestors(target)
    elif direction == "downstream":
        direct = graph.children(target)
        all_related = graph.descendants(target)
    else:
        raise ValueError(f"Invalid direction: {direction}")

    return {
        "target": _format_node(graph, target),
        "direction": direction,
        "direct": [_format_node(graph, n) for n in sorted(direct)],
        "all": [_format_node(graph, n) for n in sorted(all_related)],
        "stats": {
            "direct_count": len(direct),
            "total_count": len(all_related),
        },
        "artifact": {
            "generated_at": metadata.get("generated_at", ""),
            "schema_version": metadata.get("schema_version", ""),
        },
    }


def lineage_stats(artifact_path: str) -> dict[str, Any]:
    """Return summary statistics for a lineage artifact."""
    graph, metadata = _get_cached_graph(artifact_path)
    return {
        "nodes": graph.node_count,
        "edges": graph.edge_count,
        "schema_version": metadata.get("schema_version", ""),
        "generated_at": metadata.get("generated_at", ""),
        "manifest_sha": metadata.get("manifest_sha", ""),
        "warnings": metadata.get("warnings", []),
    }


def find_artifact(explicit: str | None = None) -> str:
    """Wrapper exposing the finder for CLI consumers."""
    return find_lineage_artifact(explicit_path=explicit)
